name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish NuGet Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Check for changes in project files
        id: check-changes
        run: |
          # Проверяем, есть ли предыдущий коммит
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          else
            echo "No previous commit found. Assuming all files are changed."
            CHANGED_FILES=$(git ls-files)
          fi

          echo "All changed files: $CHANGED_FILES"

          # Фильтруем несущественные файлы
          ESSENTIAL_CHANGES=$(echo "$CHANGED_FILES" | grep -Ev "(\.editorconfig|\.gitignore|\.yml|\.sln|^\.github/)")

          echo "Filtered essential changes: $ESSENTIAL_CHANGES"

          # Проверяем, есть ли изменения в проектах
          if echo "$ESSENTIAL_CHANGES" | grep -Eq "src/WC.Library.Data|src/WC.Library.Data.Abstractions|src/WC.Library.Data.PostgreSql"; then
            echo "Changes detected in project files."
            echo "should_publish=true" >> $GITHUB_ENV
          else
            echo "No essential changes detected. Skipping publish."
            echo "should_publish=false" >> $GITHUB_ENV
          fi
      
      - name: Get latest version for WC.Library.Data
        if: env.should_publish == 'true'
        id: get-version-data
        run: |
          PACKAGE_ID="wc.library.data"
          PACKAGE_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID}/index.json | jq -r '.versions[-1]')

          if [ -z "$PACKAGE_VERSION" ]; then
            echo "No versions found on NuGet for $PACKAGE_ID. Starting from 1.0.0."
            NEW_VERSION="1.0.0"
          else
            echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
            NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "New version for $PACKAGE_ID: $NEW_VERSION"
          echo "data_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Get latest version for WC.Library.Data.Abstractions
        if: env.should_publish == 'true'
        id: get-version-abstractions
        run: |
          PACKAGE_ID="wc.library.data.abstractions"
          PACKAGE_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID}/index.json | jq -r '.versions[-1]')

          if [ -z "$PACKAGE_VERSION" ]; then
            echo "No versions found on NuGet for $PACKAGE_ID. Starting from 1.0.0."
            NEW_VERSION="1.0.0"
          else
            echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
            NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "New version for $PACKAGE_ID: $NEW_VERSION"
          echo "abstractions_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Get latest version for WC.Library.Data.PostgreSql
        if: env.should_publish == 'true'
        id: get-version-postgresql
        run: |
          PACKAGE_ID="wc.library.data.postgresql"
          PACKAGE_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID}/index.json | jq -r '.versions[-1]')

          if [ -z "$PACKAGE_VERSION" ]; then
            echo "No versions found on NuGet for $PACKAGE_ID. Starting from 1.0.0."
            NEW_VERSION="1.0.0"
          else
            echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
            NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "New version for $PACKAGE_ID: $NEW_VERSION"
          echo "postgresql_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and pack WC.Library.Data
        if: env.should_publish == 'true'
        run: |
          dotnet pack src/WC.Library.Data/WC.Library.Data.csproj -c Release -o ./out /p:Version=${{ env.data_version }}

      - name: Build and pack WC.Library.Data.Abstractions
        if: env.should_publish == 'true'
        run: |
          dotnet pack src/WC.Library.Data.Abstractions/WC.Library.Data.Abstractions.csproj -c Release -o ./out /p:Version=${{ env.abstractions_version }}

      - name: Build and pack WC.Library.Data.PostgreSql
        if: env.should_publish == 'true'
        run: |
          dotnet pack src/WC.Library.Data.PostgreSql/WC.Library.Data.PostgreSql.csproj -c Release -o ./out /p:Version=${{ env.postgresql_version }}

      - name: Publish packages to NuGet
        if: env.should_publish == 'true'
        run: |
          set -e  # Прерываем выполнение скрипта при ошибке
          dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
