name: Publish Libraries to NuGet

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
      # Проверка кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Настройка NuGet-источников
      - name: Configure NuGet sources
        run: |
          if ! dotnet nuget list source | grep -q "nuget.org"; then
            dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org
          fi
          if ! dotnet nuget list source | grep -q "LocalPackages"; then
            dotnet nuget add source ./artifacts --name LocalPackages
          fi

      # Получение версии для WC.Library.Data.Abstractions
      - name: Get latest version for WC.Library.Data.Abstractions
        id: get-version-abstractions
        run: |
          PACKAGE_ID="wc.library.data.abstractions"
          PACKAGE_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID}/index.json | jq -r '.versions[-1]')

          if [ -z "$PACKAGE_VERSION" ]; then
            echo "No versions found on NuGet for $PACKAGE_ID. Starting from 1.0.0."
            NEW_VERSION="1.0.0"
          else
            echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
            NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "abstractions_version=$NEW_VERSION" >> $GITHUB_ENV

      # Сборка и публикация WC.Library.Data.Abstractions в локальный репозиторий
      - name: Build and publish WC.Library.Data.Abstractions locally
        run: |
          dotnet build src/WC.Library.Data.Abstractions/WC.Library.Data.Abstractions.csproj --configuration Release
          dotnet pack src/WC.Library.Data.Abstractions/WC.Library.Data.Abstractions.csproj --configuration Release --output ./artifacts /p:Version=$abstractions_version

      # Обновление зависимости WC.Library.Data.Abstractions в WC.Library.Data
      - name: Update WC.Library.Data dependency version
        run: |
          # Добавляем зависимость из локального репозитория
          dotnet add src/WC.Library.Data/WC.Library.Data.csproj package wc.library.data.abstractions --version ${{ env.abstractions_version }} --source ./artifacts

          # Выполняем восстановление всех зависимостей, включая nuget.org
          dotnet restore src/WC.Library.Data/WC.Library.Data.csproj

      # Получение версии для WC.Library.Data
      - name: Get latest version for WC.Library.Data
        id: get-version-data
        run: |
          PACKAGE_ID="wc.library.data"
          PACKAGE_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID}/index.json | jq -r '.versions[-1]')

          if [ -z "$PACKAGE_VERSION" ]; then
            echo "No versions found on NuGet for $PACKAGE_ID. Starting from 1.0.0."
            NEW_VERSION="1.0.0"
          else
            echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
            NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "data_version=$NEW_VERSION" >> $GITHUB_ENV

      # Сборка и публикация WC.Library.Data
      - name: Build and publish WC.Library.Data
        run: |
          dotnet build src/WC.Library.Data/WC.Library.Data.csproj --configuration Release
          dotnet pack src/WC.Library.Data/WC.Library.Data.csproj --configuration Release --output ./artifacts /p:Version=$data_version
          dotnet nuget push ./artifacts/WC.Library.Data.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate

      # Публикация WC.Library.Data.Abstractions в NuGet
      - name: Publish WC.Library.Data.Abstractions
        run: |
          dotnet nuget push ./artifacts/WC.Library.Data.Abstractions.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Get latest version for WC.Library.Data.PostgreSql
        id: get-version-postgresql
        run: |
          PACKAGE_ID="wc.library.data.postgresql"
          PACKAGE_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID}/index.json | jq -r '.versions[-1]')

          if [ -z "$PACKAGE_VERSION" ]; then
            echo "No versions found on NuGet for $PACKAGE_ID. Starting from 1.0.0."
            NEW_VERSION="1.0.0"
          else
            echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
            NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
          fi

          echo "postgresql_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and publish WC.Library.Data.PostgreSql
        run: |
          dotnet build src/WC.Library.Data.PostgreSql/WC.Library.Data.PostgreSql.csproj --configuration Release
          dotnet pack src/WC.Library.Data.PostgreSql/WC.Library.Data.PostgreSql.csproj --configuration Release --output ./artifacts /p:Version=$postgresql_version
          dotnet nuget push ./artifacts/WC.Library.Data.PostgreSql.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
